name: Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@hexlabsio'

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PACKAGES_TOKEN}}

      - name: Lint
        run: npm run lint

      - name: Production Build
        run: npm run build && npm run build:sdk
        env:
          API_VERSION: 1.0.${{ github.run_number }}

      - name: Test
        run: npm test

      - name: Upload Distribution
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Upload Distribution
        uses: actions/upload-artifact@v2
        with:
          name: dist-sdk
          path: dist-sdk/

      - name: Upload Generated
        uses: actions/upload-artifact@v2
        with:
          name: generated
          path: generated/

  release-sdk:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hexlabsio'

      - uses: actions/download-artifact@v2

      - name: Set Version
        run: npm --no-git-tag-version version 1.0.${{ github.run_number }}
        working-directory: dist-sdk

      - name: Release
        run: npm publish
        working-directory: dist-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@hexlabsio'

      - name: Install
        run: npm ci && npm install -g @hexlabs/kloudformation-ts
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PACKAGES_TOKEN}}

      - uses: actions/download-artifact@v2

      - name: Deploy Stack
        run: |
          kloudformation deploy \
          -s klouds-users-$ENVIRONMENT \
          -f $(pwd)/dist \
          -b hexlabs-deployments \
          -p klouds-template-$ENVIRONMENT \
          klouds-template-$ENVIRONMENT \
          $(pwd)/stack/stack.ts
        env:
          ENVIRONMENT: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy-prod:
    if: github.event.action == 'published'
    needs: deploy-dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@hexlabsio'

      - name: Install
        run: npm ci && npm install -g @hexlabs/kloudformation-ts
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PACKAGES_TOKEN}}

      - uses: actions/download-artifact@v2

      - name: Deploy Stack
        run: |
          kloudformation deploy \
          -s klouds-users-$ENVIRONMENT \
          -f $(pwd)/dist \
          -b hexlabs-deployments-prod \
          -p klouds-template-$ENVIRONMENT \
          klouds-template-$ENVIRONMENT \
          $(pwd)/stack/stack.ts
        env:
          ENVIRONMENT: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_KEY }}
